void TimeAdvance(const double Psy_L,
                  const double Psy_H,
                  const int N_x,
                  const int N_y,
                  const int num_ghost_cell,
                  const double gamma,
                  double dt,
                  double *U_OLD,
                  double *U_TMP,
                  double *U_NEW,
                  double *XYCOORD,
                  double *SCHEME_IDX);


                  
